package com.bountyly.connect.util;

public class SQLQueries {
    public final static String FIND_ALL_USERS = "SELECT USER_ID, USER_NAME, USER_EMAIL, USER_MOBILE, USER_ADDRESS_1, USER_ADDRESS_2, USER_CODE, USER_GROUP, USER_STATUS, USER_LAST_LOGGED_IN, USER_CREATED_ON, USER_MODIFIED_ON, USER_CREATED_BY, USER_MODIFIED_BY, USER_WALLET_BALANCE, USER_INTRODUCED_BY FROM BOUNTYLY_CONNECT.USERS";
    public final static String FIND_USER_BY_USER_ID = "SELECT USER_ID, USER_NAME, USER_EMAIL, USER_MOBILE, USER_ADDRESS_1, USER_ADDRESS_2, USER_CODE, USER_GROUP, USER_STATUS, USER_LAST_LOGGED_IN, USER_CREATED_ON, USER_MODIFIED_ON, USER_CREATED_BY, USER_MODIFIED_BY, USER_WALLET_BALANCE, USER_INTRODUCED_BY FROM BOUNTYLY_CONNECT.USERS WHERE USER_ID=?::bigint";
    public final static String FIND_USER_BY_MOBILE_NO  = "SELECT USER_ID, USER_NAME, USER_EMAIL, USER_MOBILE, USER_ADDRESS_1, USER_ADDRESS_2, USER_CODE, USER_GROUP, USER_STATUS, USER_LAST_LOGGED_IN, USER_CREATED_ON, USER_MODIFIED_ON, USER_CREATED_BY, USER_MODIFIED_BY, USER_WALLET_BALANCE, USER_INTRODUCED_BY FROM BOUNTYLY_CONNECT.USERS WHERE USER_MOBILE=?";
    public final static String CREATE_USER="INSERT INTO BOUNTYLY_CONNECT.USERS (USER_ID, USER_NAME, USER_EMAIL, USER_MOBILE, USER_ADDRESS_1, USER_ADDRESS_2, USER_CODE, USER_GROUP, USER_STATUS, USER_CREATED_ON, USER_CREATED_BY, USER_WALLET_BALANCE, USER_INTRODUCED_BY) VALUES(nextval('BOUNTYLY_CONNECT.users_id_seq'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
    public final static String UPDATE_USER="UPDATE BOUNTYLY_CONNECT.USERS SET  USER_NAME=?, USER_EMAIL=?, USER_MOBILE=?, USER_ADDRESS_1=?, USER_ADDRESS_2=?, USER_CODE=?, USER_GROUP=?, USER_STATUS=?, USER_MODIFIED_ON=LOCALTIMESTAMP, USER_MODIFIED_BY=?, USER_INTRODUCED_BY=? WHERE USER_ID=?";
    public final static String DELETE_USER="DELETE FROM BOUNTYLY_CONNECT.USERS WHERE USER_ID=?";
}
